### ISSUE TITLE
Configuration issue

### ISSUE THREAD

**Issue by MohammadAliK** [robertlevonyan/CameraXDemo#10]
FAILURE: Build failed with an exception.

* Where:
Build file '/home/Library/CameraXDemo-master/CameraXDemo/app/build.gradle' line: 1

* What went wrong:
A problem occurred evaluating project ':app'.
> Failed to apply plugin [id 'com.android.internal.version-check']
   > Minimum supported Gradle version is 6.5. Current version is 6.1.1. If using the gradle wrapper, try editing the distributionUrl in /home/Library/CameraXDemo-master/CameraXDemo/gradle/wrapper/gradle-wrapper.properties to gradle-6.5-all.zip

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 11s

**Comment by robertlevonyan** [comment]
in your graddle-wrapper.propertios file update the distriubution version to 6.8-bin or 6.8-all

**Comment by MohammadAliK** [comment]
But file is missing there. @robertlevonyan

**Comment by robertlevonyan** [comment]
@MohammadAliK pushed :)
