### ISSUE TITLE
Preview freezes while recording video on Samsung tablet (SM-T580)

### ISSUE THREAD

**Issue by uchamad** [robertlevonyan/CameraXDemo#5]
I am testing the app on SM-T580 and while recording video the preview freezes and the video does not get recorded.

It gets frozen when record button is pressed. I believe this happening while the camera is autofocusing. If I wait for the camera to finish focusing and then press record button, it works as expected. 

The app works perfectly fine on my other device where the camera has no autofocus function.

Is there a way to turn the autofocus off.

**Comment by robertlevonyan** [comment]
The demo project is updated. Please check it.
