### ISSUE TITLE
Is it possible to use CameraX to access ToF (Time of Flight) sensor depth map?

### ISSUE THREAD

**Issue by agGitHub** [robertlevonyan/CameraXDemo#7]
Hi,

I wonder if it is possible to use CameraX to access ToF (Time of Flight) sensor depth map.

Or should I use Camera2 ?

Thanks

**Comment by robertlevonyan** [comment]
It is possible to get a Camera instance using CameraX. Maybe you can find ToF data from there. Or meybe there should be a vendor extension for that reason.
